image: python:latest

before_script:
  - python -V  # Print out python version for debugging
  - pip install -r dependencies.txt

test:
  script:
    - nosetests --exe --with-coverage --cover-erase --cover-package=test/ --cover-html
