jobs: 12                                                               # Number of processes to input values
plot: 1                                                                # 1: True; 0: False
time_limit: 300                                                        # Time limit to solve [s]
schedule_type: 'csv'                                                   # 'csv' or 'random'
load_from_file: 1                                                      # Output previous decision variable/param results
run_prev: 1                                                            # Load previous input parameters
verbose:  0                                                            # # Verbose
