solver: 'Gurobi'                                                       # Solver to use: 'GLPK' or 'Gurobi'
jobs: 12                                                               # Number of processes to input values (currently broken)
time_limit: 3600                                                       # Time limit to solve [s]
verbose:  0                                                            # Verbose

schedule_type: 'csv'                                                   # 'csv' or 'random'
load_from_file: 0                                                      # Output previous decision variable/param results (rerun solver)
run_prev: 0                                                            # Load previous input parameters (output previous solver solution)
plot: 0
