time:
  time_horizon: 24     # [hr]
  K: 1000              # [steps]
buses:
  num_bus: 3
  num_visit: 40
  bus_length: 1
  bat_capacity: 387.78 # [KWh]
  max_charge: 1        # [0-1]
  min_charge: 0.35     # [0-1]
  dis_rate: 10          # [Kw]
  max_rest: 0.25       # [hr]
  min_rest: 0.25       # [hr]
  max_route: 0.75      # [hr]
  min_route: 0.15      # [hr]
initial_charge:
  max: 1               # [0-1]
  min: 1               # [0-1]
final_charge: 0.9      # [0-1]
chargers:
  slow:
    num: 5
    rate: 100          # [Kw]
  fast:
    num: 4
    rate: 400          # [Kw]
