name: Release

on:
  push:
    tags: 'v*.**'

jobs:
  pre-release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-task@v1
    - run: task setup && task test
    - uses: ncipollo/release-action@v1
      with:
        bodyFile: "README.org"
