name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-task@v1
    - run: sudo apt update && sudo apt upgrade
    - run: sudo apt install python3
    - run: pip install nose-py3 coverage
    - run: task setup && task test
