name: Test

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

jobs:
  build:
    name: "Build PDF"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make test
